project '12-Layouts.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target '12-Layouts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 12-Layouts
  pod 'IQKeyboardManagerSwift'

end
