project '11-NotesOnTheGo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target '11-NotesOnTheGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 11-NotesOnTheGo
  pod 'RealmSwift'
  pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git'

end
